abstract: Read/Write .ini style files with as little code as possible
author: 'Adam Kennedy, L<http://ali.as/>, cpan@aliI<.>as'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.50
license: perl
name: Config-Tiny
no_index:
  directory:
    - inc
    - t
requires:
  FindBin: 0
  perl: 5.004
version: 2.04
