abstract: Read/Write .ini style files with as little code as possible
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  ExtUtils::MakeMaker: 6.11
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Config-Tiny
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.004
version: 2.10
