
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 2.07
name: Config-Tiny
author: Adam Kennedy, L<http://ali.as/>, cpan@aliI<.>as
license: perl
build_requires: 
  Test::More: 0.47
requires: 
  perl: 5.004
abstract: Read/Write .ini style files with as little code as possible
